### ISSUE TITLE
保存的图片是空白的，是在最外层添加的事件，点击后调用子组件saveImage方法

### ISSUE THREAD

**Issue by nzjcnjzx** [WGinit/mini-poster#7]

**Comment by nzjcnjzx** [comment]
绘制图形后，开发者工具可以保存在本地， 真机上不行，这是为什么呢

**Comment by nzjcnjzx** [comment]
let imageList = customData.imageList
      let textList = customData.textList
      if (!imageList.length) {
        return
      }
customData这个变量没有赋值的地方
imageList的值始终都是空数组 下面的逻辑都不会执行了？

**Comment by WGinit** [comment]
已优化，谢谢反馈，检查下是否包含网络图片，小程序的canvas绘制图片，图片路径必须为本地的路径，而不能是网络路径

**Comment by suiyingsky** [comment]
往往很多时候需要根据网络图片来生成海报，在保存到

**Comment by MakerGYT** [comment]
试试这个[share](https://github.com/makergyt/share),会提前把网络图片自动下载再绘制

**Comment by WGinit** [comment]
已修复
