### ISSUE TITLE
保存出来的图片是空白的，无网络图片

### ISSUE THREAD

**Issue by 804657038** [WGinit/mini-poster#8]
![图片](https://user-images.githubusercontent.com/23028100/87741558-6440e900-c817-11ea-9135-81bce59d8fce.png)
![图片](https://user-images.githubusercontent.com/23028100/87741568-6acf6080-c817-11ea-86fb-ea53c73339c5.png)

**Comment by MakerGYT** [comment]
试试这个[share](https://github.com/makergyt/share),会提前把网络图片自动下载再绘制

**Comment by WGinit** [comment]
@804657038 这里的图片路径是网络路径，绘图才需要用到的图片本地路径，这个组件会提前downLoad, 前提是需要在MP 后台配置下图片域名

**Comment by WGinit** [comment]
该问题已修复
